
import { faker } from "@faker-js/faker";
export default (user,count,invoicetypeIds,identifiertypeIds,thefirstsuppliercontactnumberIds,suppliercountrynameIds,supplierstatenameIds,buyeridentifiertypeIds,buyercountrynameIds,buyerstatenameIds,thefirstbuyercontactnumberIds,invoicecurrencyIds,frequencyofbillingIds,paymentmodeIds,shippingrecipientidentifiertypeIds,invoicelineclassificationIds,measurementIds,countryoforiginIds,taxtypeIds,detailtaxtypeIds) => {
    let data = [];
    for (let i = 0; i < count; i++) {
        const fake = {
noff: faker.lorem.sentence(""),
invoicetype: invoicetypeIds[i % invoicetypeIds.length],
invoicedateandtime: faker.lorem.sentence(""),
originaleinvoicereferencenumber: faker.lorem.sentence(""),
suppliername: faker.lorem.sentence(""),
suppliertin: faker.lorem.sentence(""),
suppliersstregistrationnumber: faker.lorem.sentence(""),
identifiertype: identifiertypeIds[i % identifiertypeIds.length],
identifiernumber: faker.lorem.sentence(""),
suppliermsiccode: faker.lorem.sentence(""),
suppliertourismtaxregistrationnumber: faker.lorem.sentence(""),
supplierbusinessactivitydescription: faker.lorem.sentence(""),
supplieremail: faker.lorem.sentence(""),
thefirstsuppliercontactnumber: thefirstsuppliercontactnumberIds[i % thefirstsuppliercontactnumberIds.length],
suppliercontactnumber: faker.lorem.sentence(""),
suppliercountryname: suppliercountrynameIds[i % suppliercountrynameIds.length],
supplierstatename: supplierstatenameIds[i % supplierstatenameIds.length],
suppliercityname: faker.lorem.sentence(""),
supplierpostalzone: faker.lorem.sentence(""),
supplieradressline0: faker.lorem.sentence(""),
supplieradressline1: faker.lorem.sentence(""),
supplieraddressline2: faker.lorem.sentence(""),
buyername: faker.lorem.sentence(""),
buyertin: faker.lorem.sentence(""),
buyersstregistrationnumber: faker.lorem.sentence(""),
buyeridentifiertype: buyeridentifiertypeIds[i % buyeridentifiertypeIds.length],
buyerbusinessregistrationnumber: faker.lorem.sentence(""),
buyeremail: faker.lorem.sentence(""),
buyercountryname: buyercountrynameIds[i % buyercountrynameIds.length],
buyerstatename: buyerstatenameIds[i % buyerstatenameIds.length],
buyercityname: faker.lorem.sentence(""),
buyerpostalzone: faker.lorem.sentence(""),
buyeraddressline0: faker.lorem.sentence(""),
buyeraddressline1: faker.lorem.sentence(""),
buyeraddressline2: faker.lorem.sentence(""),
thefirstbuyercontactnumber: thefirstbuyercontactnumberIds[i % thefirstbuyercontactnumberIds.length],
buyercontactnumber: faker.lorem.sentence(""),
invoicecurrency: invoicecurrencyIds[i % invoicecurrencyIds.length],
currencyexchangerate: faker.lorem.sentence(""),
frequencyofbilling: frequencyofbillingIds[i % frequencyofbillingIds.length],
billingperiodstartdate: faker.lorem.sentence(""),
billingperiodenddate: faker.lorem.sentence(""),
paymentmode: paymentmodeIds[i % paymentmodeIds.length],
supplierbankaccountnumber: faker.lorem.sentence(""),
paymentterms: faker.lorem.sentence(""),
prepaymentamount: faker.lorem.sentence(""),
prepaymentdate: faker.lorem.sentence(""),
prepaymentreferencenumber: faker.lorem.sentence(""),
shippingrecipientname: faker.lorem.sentence(""),
shippingrecipientcountryname: faker.lorem.sentence(""),
shippingrecipientstatename: faker.lorem.sentence(""),
shippingrecipientcityname: faker.lorem.sentence(""),
shippingrecipientpostalzone: faker.lorem.sentence(""),
shippingrecipientaddressline0: faker.lorem.sentence(""),
shippingrecipientaddressline1: faker.lorem.sentence(""),
shippingrecipientaddressline2: faker.lorem.sentence(""),
shippingrecipienttin: faker.lorem.sentence(""),
shippingrecipientidentifiertype: shippingrecipientidentifiertypeIds[i % shippingrecipientidentifiertypeIds.length],
shippingrecipientbusinessregistrationnumber: faker.lorem.sentence(""),
billreferencenumber: faker.lorem.sentence(""),
referencenumberofcustomsformno1: faker.lorem.sentence(""),
incoterms: faker.lorem.sentence(""),
freetradeagreementinformation: faker.lorem.sentence(""),
authorisationnumberforcertifiedexporter: faker.lorem.sentence(""),
referencenumberofcustomsformno2: faker.lorem.sentence(""),
invoicelinenumber: faker.lorem.sentence("8"),
invoicelineclassification: invoicelineclassificationIds[i % invoicelineclassificationIds.length],
productname: faker.lorem.sentence(""),
quantity: faker.lorem.sentence(""),
unitprice: faker.lorem.sentence(""),
measurement: measurementIds[i % measurementIds.length],
subtotal: faker.lorem.sentence(""),
countryoforigin: countryoforiginIds[i % countryoforiginIds.length],
pretotalexcludingtax: faker.lorem.sentence(""),
taxtype: taxtypeIds[i % taxtypeIds.length],
taxrate: faker.lorem.sentence(""),
taxamount: faker.lorem.sentence(""),
taxdescription: faker.lorem.sentence(""),
taxexemptiondetails: faker.lorem.sentence(""),
taxexemptionamount: faker.lorem.sentence(""),
discountrate: faker.lorem.sentence(""),
discountamount: faker.lorem.sentence(""),
discountdescription: faker.lorem.sentence(""),
feeorchargerate: faker.lorem.sentence(""),
feeorchargeamount: faker.lorem.sentence(""),
feeorchargedescription: faker.lorem.sentence(""),
detailtaxtype: detailtaxtypeIds[i % detailtaxtypeIds.length],
detailtotaltaxamountpertaxtype: faker.lorem.sentence(""),
detailtotaltaxableamount: faker.lorem.sentence(""),
detailsoftaxexemption: faker.lorem.sentence(""),
amountexemptedfromtax: faker.lorem.sentence(""),
additionaldiscountamount: faker.lorem.sentence(""),
additionaldiscountdescription: faker.lorem.sentence("8"),
additionalfeeamount: faker.lorem.sentence(""),
additionalfeedescription: faker.lorem.sentence("8"),
otherfeeorchargeamounts: faker.lorem.sentence(""),
othrefeeorchargedescription: faker.lorem.sentence(""),
totaldiscountvalue: faker.lorem.sentence(""),
totalfeeorchargeamount: faker.lorem.sentence(""),
totaltaxamount: faker.lorem.sentence(""),
totalexcludingtax: faker.lorem.sentence(""),
totalnetamount: faker.lorem.sentence(""),
totalincludingtax: faker.lorem.sentence(""),
roundingamount: faker.lorem.sentence(""),
totalpayableamount: faker.lorem.sentence(""),
invoicenumber: faker.lorem.sentence(""),

updatedBy: user._id,
createdBy: user._id
        };
        data = [...data, fake];
    }
    return data;
};
